DEFAULT_GRID_WIDTH = 3.14 * 2
DEFAULT_GRID_HEIGHT = 500

DEFAULT_X_AXIS_TICKS = 10
X_AXIS_TICK_LABEL_FREQ = 3  # Label frequency of 2 means every other tick is labeled
X_AXIS_UNIT = 'S'

DEFAULT_Y_AXIS_TICKS = 10
Y_AXIS_TICK_LABEL_FREQ = 3
Y_AXIS_UNIT = 'V'
