DEFAULT_GRID_WIDTH = 10
DEFAULT_GRID_HEIGHT = 10

DEFAULT_X_AXIS_TICKS = 10
X_AXIS_TICK_LABEL_FREQ = 2  # Label frequency of 2 means every other tick is labeled
X_AXIS_UNIT = 'S'
X_AXIS_PADDING = 20

DEFAULT_Y_AXIS_TICKS = 10
Y_AXIS_TICK_LABEL_FREQ = 2
Y_AXIS_UNIT = 'V'
Y_AXIS_PADDING = 10
